name: Lint Tokens

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - tokens/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: tokens

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: tokens/.node-version
          cache: 'npm'
          cache-dependency-path: tokens/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: tsc
