name: "BCC common components package release 🚀"

on:
  push:
    branches:
      - main
jobs:
    release:
        permissions:
          contents: write
        name: 🚀 release
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v2.1.1
            - name: 🟢 node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org

            - name: 'cat package.json'
              run: cat ./package.json

            - name: 'Automated Version Bump'
              id: version-bump
              uses: 'phips28/gh-action-bump-version@master'
              with:
                tag-prefix: 'v'
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: 'cat package.json'
              run: cat ./package.json

            # - name: Increment package.json version
            #   uses: jaywcjlove/github-action-package@main
            #   with:
            #     version: repository.type,repository.url,keywords

            - name: 🚀 publish
              run: npm publish --access public
              working-directory: componentsPackage
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}