name: "BCC common components package release 🚀"

on:
    push:
        branches: 
         - main
        paths:
          - "bcc-design/tokens/**"
      workflow_dispatch:

jobs:
    release:
        name: 🚀 release
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v2.1.1
            - name: 🟢 node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
            - name: 🚀 publish
              run: npm publish --access public
              working-directory: BCCComponents
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}