name: Run Unit Tests

on:
  push:
    branches-ignore:
      - 'main'
  workflow_call:

defaults:
  run:
    working-directory: vue-components

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: vue-components/.node-version
          cache: 'npm'
          cache-dependency-path: vue-components/package-lock.json
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test:unit
